### ISSUE TITLE
BUG: /api/health/fred is showing a 400 error

### ISSUE THREAD

**Issue by wentbackward** [PGALLC/crisis_monitor#23]
**Original Bug Report:**
This was the original bug report before the issue was trampled on. Luckily history is maintained:

Response: `<html><body>[/+]
[+][/+]
[+]status | "error"[/+]
[+]-- | --[/+]
[+]message | "FRED API error: 400 Bad Request"[/+]
[+][/+]
[+]</body>[/+]
[+]</html>`[/+]

Running `curl "https://api.stlouisfed.org/fred/series/observations?series_id=DGS10&api_key=REDACTED&file_type=json&sort_order=desc&limit=3"`
 shows a good result

`{"realtime_start":"2026-02-27","realtime_end":"2026-02-27","observation_start":"1600-01-01","observation_end":"9999-12-31","units":"lin","output_type":1,"file_type":"json","order_by":"observation_date","sort_order":"desc","count":16738,"offset":0,"limit":3,"observations":[{"realtime_start":"2026-02-27","realtime_end":"2026-02-27","date":"2026-02-26","value":"4.02"},{"realtime_start":"2026-02-27","realtime_end":"2026-02-27","date":"2026-02-25","value":"4.05"},{"realtime_start":"2026-02-27","realtime_end":"2026-02-27","date":"2026-02-24","value":"4.04"}]}`

Additional comments later:

The functional tests are failing during the deployment pipeline. The deployment to Test completes, but the `npm run test:functional` step fails, causing the pipeline to halt before the SRE gate.

**Platform Engineer Note:**
The application code is missing the required routes and tests. Coder and Reviewer need to address this.

**Comment by wentbackward** [comment]
> **SRE: please verify the env var is actually present and correct in the running pod:**
> 
> kubectl exec -n crisis-monitor-test deployment/crisis-monitor -- env | grep FRED
> 
> This will confirm whether:
> 
>     1. `FRED_API_KEY` is set in the pod at all
> 
>     2. The value looks like a valid API key (not empty, not a placeholder)

SRE here: I've checked this and the key is precisely the right key. I even copy pasted the key returned by K8s and made a call to FRED which succeeded.

**Comment by C3P-Coder** [comment]
## Coder — Root Cause Confirmed and Fixed (PR #29)

**Root cause: `config.ts` still references `NAPM`, which FRED removed in June 2016.**

Here is what happened across the two PRs:

| Change | PR #27 (merged) | PR #29 (open) |
|---|---|---|
| `.trim()` on `FRED_API_KEY` | ✅ | — |
| Smoke tests with `BASE_URL` | ✅ | — |
| **`NAPM` → `IPMAN` in `config.ts`** | ❌ missed | ✅ |
| Version + DGS10 health probe | ❌ missed | ✅ |
| `gitSha` deployment gate | ❌ missed | ✅ |

The NAPM fix was committed to branch `fix/STORY-001e-smoke-and-key-trim` **after** PR #27 was merged, so it was never included in main. The deployed code has always been calling `NAPM`, which FRED unconditionally rejects with HTTP 400 — regardless of the API key, which the SRE correctly confirmed is valid.

**PR #29 delivers all three missing commits:** https://github.com/PGALLC/crisis_monitor/pull/29

Once merged and deployed, `/api/health/fred` will:
1. Call `DGS10` only (not all four connectors — no single bad series can break the endpoint)
2. Return `version` and `gitSha` for post-deploy verification
3. Allow smoke tests to assert `EXPECTED_GIT_SHA` matches the running image

**Platform Engineer:** after PR #29 merges, Dockerfile needs `ARG GIT_SHA=dev` / `ENV GIT_SHA=$GIT_SHA` and the deploy scripts need `--build-arg GIT_SHA=$(git rev-parse --short HEAD)` and `EXPECTED_GIT_SHA=<sha>` on the smoke test run.

**Comment by wentbackward** [comment]
## Reviewer — Orchestration Plan

**@C3P-Coder and @C3P-Platform — assigning tasks below. Issue #23 remains open until both roles deliver and the pipeline is green.**

---

### Root Cause Summary

The CrashLoopBackOff (`Cannot find module '/app/dist/server.js'`) was introduced in PR #29 by `import packageJson from '../package.json'` in `src/app.ts`. This import reaches outside `src/`, shifting TypeScript's inferred `rootDir` from `src/` to the project root. The compiled output silently moves from `dist/server.js` → `dist/src/server.js`, but the Dockerfile CMD still points to `dist/server.js`. The build succeeds, the image is wrong, the pod crashes on startup.

This is a **two-role fix** that must be coordinated before any further deployment.

---

### Task List

#### @C3P-Coder
- [ ] Remove `import packageJson from '../package.json'` from `src/app.ts`
- [ ] Replace the `version` field with `process.env.VERSION ?? 'unknown'`
- [ ] Add `"rootDir": "./src"` explicitly to `tsconfig.json` — this makes the compiler error loudly if any future import escapes `src/`, preventing a silent recurrence
- [ ] Update `fredHealth.test.ts` — the `version` assertion regex `/^\d+\.\d+\.\d+$/` will not match `'unknown'`; mock `process.env.VERSION` in tests (e.g. `'0.1.0'`) via `beforeEach`/`afterEach`

#### @C3P-Platform
- [ ] Add `VERSION` and `GIT_SHA` build args to `Dockerfile`:
  ```dockerfile
  ARG GIT_SHA=dev
  ARG VERSION=unknown
  ENV GIT_SHA=$GIT_SHA
  ENV VERSION=$VERSION
  ```
- [ ] Update `deploy_test.sh` — inject both build args and export test smoke vars:
  ```bash
  SHA=$(git rev-parse --short HEAD)
  # Pass to docker build (in build-and-push CI step):
  #   --build-arg GIT_SHA=$SHA --build-arg VERSION=$(node -p "require('./package.json').version")
  export EXPECTED_GIT_SHA=$SHA
  TEST_IP=$(kubectl get service crisis-monitor -n crisis-monitor-test \
    -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
  export BASE_URL="http://${TEST_IP}"
  ```
- [ ] Confirm `deploy_prod.sh` already has `BASE_URL` set (PR #28) — add `EXPECTED_GIT_SHA` export there too
- [ ] The `--build-arg` flags must be added to the `docker/build-push-action` step in `.github/workflows/ci-cd.yml`

---

### Sequencing

The Coder and Platform Engineer should raise **separate PRs** for their respective scopes. As Reviewer I will not approve either until both are open, cross-checked, and the pipeline is green on the Coder's PR. Per C3P cross-role protocol, I will add a task list to the Coder's PR tracking both deliverables before merge.

Do not attempt another deployment until both PRs are merged.
